AlbumPhoto/Models/AlbumVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AlbumPhoto.Models
{
    public class AlbumVM
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public IFormFile PhotoLink { get; set; }
    }
}

AlbumPhoto/Models/ErrorViewModel.cs
using System;

namespace AlbumPhoto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlbumPhoto/Models/PhotoMV.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AlbumPhoto.Models
{
    public class PhotoMV
    {
        [Required]
        public int AlbumId { get; set; }

        [Required]
        public IFormFile PhotoLink { get; set; }
    }
}

AlbumPhoto/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AlbumPhoto.Models;
using Models;
using System.IO;
using BL.services;

namespace AlbumPhoto.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAlbumBl _AlbumBL;
        public HomeController(IAlbumBl AlbumBL)
        {
            this._AlbumBL = AlbumBL;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(AlbumVM model)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            var guid = Guid.NewGuid().ToString();
            var photoName = $"{guid}_{model.PhotoLink.FileName}";
            var FilePath = $"wwwroot\\uploads\\{photoName}";
            using (var stream = new FileStream(FilePath, FileMode.Create))
            {
                model.PhotoLink.CopyTo(stream);
            }

            var album = new Album()
            {
                Name = model.Name,
                Description = model.Description,
                PhotoLink = $"/uploads/{photoName}",
            };

            _AlbumBL.Create(album);

            return RedirectToAction("Index");
        }
    }
}

AlbumPhoto/Controllers/PhotoController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AlbumPhoto.Models;
using Models;
using System.IO;
using BL.services;

namespace AlbumPhoto.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IAlbumBl _AlbumBL;
        private readonly IPhotoBL _PhotoBL;
        public PhotoController(IAlbumBl context, IPhotoBL PhotoBL)
        {
            this._AlbumBL = context;
            this._PhotoBL = PhotoBL;
        }

        public IActionResult Index(int id)
        {
            var album = _AlbumBL.Get(id);
            return View(album);
        }

        [HttpPost]
        public IActionResult Create(PhotoMV model)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            var guid = Guid.NewGuid().ToString();
            var photoName = $"{guid}_{model.PhotoLink.FileName}";
            var FilePath = $"wwwroot\\uploads\\{photoName}";
            using (var stream = new FileStream(FilePath, FileMode.Create))
            {
                model.PhotoLink.CopyTo(stream);
            }

            var picture = new Photos()
            {
                AlbumID = model.AlbumId,
                PhotoLink = $"/uploads/{photoName}",
            };

            _PhotoBL.Create(picture);

            return RedirectToAction("Index", new { id = model.AlbumId});
        }
    }
}

AlbumPhoto/ViewComponents/AlbumGaleryViewComponent.cs
using BL.services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlbumPhoto.ViewComponents
{
    [ViewComponent(Name = "AlbumGalery")]
    public class AlbumGaleryViewComponent : ViewComponent
    {
        private readonly IAlbumBl _AlbumBL;
        public AlbumGaleryViewComponent(IAlbumBl repository)
        {
            _AlbumBL = repository;
        }

        public IViewComponentResult Invoke()
        {
            var liste = _AlbumBL.GetAll();
            return View(liste);
        }
    }
}

AlbumPhoto/Views/Home/Create.cshtml
@model AlbumVM

@{
    ViewData["Title"] = "Create";
}

<h2>New Album</h2>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name">Nom </label>
        <input class="form-control" type="text" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input class="form-control" type="text" asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhotoLink">Photo</label>
        <input class="form-control" type="file" asp-for="PhotoLink" accept="image/*" />
        <span class="text-danger" asp-validation-for="PhotoLink"></span>
    </div>
    <button class="btn btn-success" type="submit">Save</button>
</form>

@*
    accept == propriete html qui va faire un sorte de telecharger que des images et aucun autre fichier.
*@

AlbumPhoto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Mon Album";
}

<div class="row">
    <div class="col-md-12">
        <br />
        <div class="well well-sm text-right">
            <a asp-action="Create" class="btn btn-primary btn-lg"> New album</a>
        </div>
        <hr />
        @await Component.InvokeAsync("AlbumGalery")
    </div>
</div>

AlbumPhoto/Views/Photo/Index.cshtml
@model Album

@{
    ViewData["Title"] = "Index";
}

<h2>@Model.Name</h2>
<p>@Model.Description</p>

<div class="row">
    @foreach (var item in Model.Photos)
    {
        <div class="col-md-4">
            <img src="@item.PhotoLink" class="img-thumbnail" />
        </div>
    }
</div>

<hr />

<div class="well">
    @Html.Partial("_Create", new PhotoMV { AlbumId = Model.ID })
</div>

AlbumPhoto/Views/Photo/_Create.cshtml
@model PhotoMV

<form asp-action="Create" method="post" enctype="multipart/form-data">
    @Html.HiddenFor(x => x.AlbumId)

    <div class="form-group">
        <label asp-for="PhotoLink">Photo</label>
        <input class="form-control" type="file" asp-for="PhotoLink" accept="image/*" />
        <span class="text-danger" asp-validation-for="PhotoLink"></span>
    </div>
    <button class="btn btn-success" type="submit">Save</button>
</form>

AlbumPhoto/Views/Shared/Components/AlbumGalery/Default.cshtml
@model List<Album>


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <a asp-controller="Photo" asp-action="Index" asp-route-id="@item.ID">
                <img src="@item.PhotoLink" class="img-thumbnail" />
            </a>
            <h3>@item.Name</h3>
            <p>@item.Description</p>
        </div>
    }
</div>

AlbumPhoto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlbumPhoto</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AlbumPhoto</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Mes Album</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AlbumPhoto</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>